welcome:
  path: /
  defaults: { _controller: FrameworkBundle:Template:template, template: 'base.html.twig' }

create:
  path: /admin/create
  defaults: { _controller: AppBundle:Workshop:create }

speaker:
  path: /admin/speaker
  defaults: { _controller: AppBundle:Workshop:speaker }

app:
  resource: '@AppBundle/Resources/config/routing.yml'
  prefix: 'workshop'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"