list:
  path: /
  defaults: { _controller: AppBundle:Workshop:list }

workshop:
  path: /{id}
  defaults: { _controller: AppBundle:Workshop:workshop }

register:
  path: /{id}/register
  defaults: { _controller: AppBundle:Workshop:register }
  requirements:
    id: \d+