services:

  workshop.services:
    class: AppBundle\Service\WorkshopService
    arguments: ["@doctrine.orm.entity_manager"]

  workshop.service.twig_extension:
    class: AppBundle\Twig\Extension\WorkshopExtension
    public: false
    arguments: ["@workshop.services"]
    tags:
      - { name: twig.extension }

  workshop.string.twig_extension:
    class: AppBundle\Twig\Extension\StringExtension
    public: false
    tags:
      - { name: twig.extension }

  workshop.import.command:
    class: AppBundle\Command\ImportApplicationsCommand
    arguments: ["@service_container", "@doctrine.orm.entity_manager"]
    tags:
     - { name: console.command }

  workshop.available_seats.validator:
    class: AppBundle\Validator\Constraints\AreSeatsAvailableValidator
    arguments: ["@workshop.services"]
    tags:
      - { name: validator.constraint_validator }

  workshop.already_registered.validator:
    class: AppBundle\Validator\Constraints\AlreadyRegisteredValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: validator.constraint_validator }